# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: GitHub workflow demo

on:
  pull_request:
  push:
    branches:
      - master

  release:
    types: [published]
#adding test comment 2
jobs:
  build:
    name: DevOps Challange
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'

    - name: Fetch next tag version detail
      uses: anothrNick/github-tag-action@1.36.0
      id: next_tag
      env:
        DRY_RUN: true

    - name: Set Build version env variable
      run: echo "BUILD_VERSION=${{ steps.next_tag.outputs.new_tag }}" >> $GITHUB_ENV

    - name: Build with Maven
      run: |
        mvn versions:set -DnewVersion=${{ env.BUILD_VERSION }}
        mvn -B install --file pom.xml

    - name: Publish to GitHub Packages
      run: mvn -B deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create a Release
      uses: elgohr/Github-Release-Action@v4
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      with:
        args: "${{ env.BUILD_VERSION }}"

    - name: Create new tag
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
